# Generated by Django 6.0.3 on 2026-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField()),
                ('image_author', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
